/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sip;

import Models.Apartamento;
import Models.Database;
import javax.swing.JOptionPane;

/**
 *
 * @author robert
 */
public class frmApartamento extends javax.swing.JFrame {

    /**
     * Creates new form Apartamento
     */
    public frmApartamento() {
        initComponents();
        this.setTitle("Registro Vivienda");
        this.setLocation(400, 200);
        new Database().onLoadTable(jTable1, "select Torre,num_apto,telefono Fijo,Citofono from apartamento");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVivienda = new javax.swing.JPanel();
        jlabel = new javax.swing.JLabel();
        txtTorre = new javax.swing.JTextField();
        txtApartm = new javax.swing.JTextField();
        txtCitofono = new javax.swing.JTextField();
        txtFijo = new javax.swing.JTextField();
        lblTorre = new javax.swing.JLabel();
        lblApto = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblExt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlVivienda.setBackground(new java.awt.Color(0, 153, 204));

        jlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabel.setText("REGISTRO DE LA VIVIENDA");

        lblTorre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTorre.setText("N° torre");

        lblApto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApto.setText("N° Apartamento");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelefono.setText("Telefono Fijo");

        lblExt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExt.setText("Citofono");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apto1.png"))); // NOI18N

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlViviendaLayout = new javax.swing.GroupLayout(pnlVivienda);
        pnlVivienda.setLayout(pnlViviendaLayout);
        pnlViviendaLayout.setHorizontalGroup(
            pnlViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViviendaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViviendaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jlabel)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlViviendaLayout.createSequentialGroup()
                        .addGroup(pnlViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlViviendaLayout.createSequentialGroup()
                                .addComponent(lblTorre)
                                .addGap(80, 80, 80)
                                .addComponent(txtTorre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlViviendaLayout.createSequentialGroup()
                                .addComponent(lblApto)
                                .addGap(30, 30, 30)
                                .addComponent(txtApartm, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlViviendaLayout.createSequentialGroup()
                                .addComponent(lblTelefono)
                                .addGap(53, 53, 53)
                                .addComponent(txtFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlViviendaLayout.createSequentialGroup()
                                .addComponent(lblExt)
                                .addGap(78, 78, 78)
                                .addComponent(txtCitofono, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlViviendaLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(btnRegistrar)))
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlViviendaLayout.setVerticalGroup(
            pnlViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViviendaLayout.createSequentialGroup()
                .addGroup(pnlViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViviendaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jlabel))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViviendaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnlViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTorre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTorre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApartm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCitofono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(btnRegistrar))
                    .addGroup(pnlViviendaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVivienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlVivienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Apartamento item = new Apartamento();
        item.setCitofono(Integer.parseInt(txtCitofono.getText().trim()));
        item.setNumeroApartamento(Integer.parseInt(txtApartm.getText().trim()));
        item.setTelefono(txtFijo.getText().trim());
        item.setTorre(txtTorre.getText().trim());
        if (item.Insertar() > 0) {
            JOptionPane.showMessageDialog(null, "Apartamento almacenado");
            this.limpiarCampos();
            new Database().onLoadTable(jTable1, "select Torre,num_apto,telefono Fijo,Citofono from apartamento");
        } else {
            JOptionPane.showMessageDialog(null, "Tenemos problemas de almacenamiento :(");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
            public void limpiarCampos(){
            txtTorre.setText("");
            txtApartm.setText("");
            txtFijo.setText("");
            txtCitofono.setText("");
            
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmApartamento().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lblApto;
    private javax.swing.JLabel lblExt;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTorre;
    private javax.swing.JPanel pnlVivienda;
    private javax.swing.JTextField txtApartm;
    private javax.swing.JTextField txtCitofono;
    private javax.swing.JTextField txtFijo;
    private javax.swing.JTextField txtTorre;
    // End of variables declaration//GEN-END:variables
}
