/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sip;

import Models.Database;
import java.awt.Image;
import javax.swing.ImageIcon;
import Models.Usuario;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.Array;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author robert
 */
public class frmRegistro extends javax.swing.JFrame {

    Database ds = new Database();
    Usuario it = new Usuario();

    public frmRegistro() {
        initComponents();
        this.setTitle("Registro Usuarios");
        this.setLocation(400, 200);
        new Database().onLoadTable(jTable2, "SELECT u.idUsuario, u.nombres,u.apellido_1 'Primer Apellido',u.apellido_2 'Segundo Apellido',u.identificacion,u.telefono,u.num_parqueadero, concat(a.torre,a.num_apto) Apartamento, r.Nombre Tipo FROM usuario u INNER JOIN apartamento a ON u.idApartamento = a.idApto INNER JOIN rol r ON r.idRol = u.idRol");

        ds.onLoadComboItems(cmbApto, "Select idApto, concat(torre, num_apto) Apartamento from apartamento", "idApto", "Apartamento");
        ds.onLoadComboItems(cmbRol, "Select idRol,  nombre Rol from rol", "idRol", "Rol");
        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                // do some actions here, for example
                // print first column value from selected row
                DefaultTableModel item = new Database().onLoadItem("Select u.*, concat(a.idApto , ' - ', a.torre, a.num_apto) Apartamento, concat(r.idRol, ' - ', r.Nombre) Rol from usuario u, apartamento a, rol r where u.idApartamento = a.idApto and r.idRol = u.idRol and idUsuario = " + jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
                // Get all the table data
                Vector data = item.getDataVector();
                // Obtener el ID del usuario
                it.ID = Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
                        
                // Colocar la informacion del usuario en el formulario
                txtNombres.setText(String.valueOf(((Vector) data.get(0)).get(1)));
                txtApellido_1.setText(String.valueOf(((Vector) data.get(0)).get(2)));
                txtApellidos2.setText(String.valueOf(((Vector) data.get(0)).get(3)));   
                txtCel.setText(String.valueOf(((Vector) data.get(0)).get(4)));
                txtId.setText(String.valueOf(((Vector) data.get(0)).get(5)));
                txtParqueadero.setText(String.valueOf(((Vector) data.get(0)).get(6)));
                cmbApto.setSelectedItem(String.valueOf(((Vector) data.get(0)).get(9)));
                cmbRol.setSelectedItem(String.valueOf(((Vector) data.get(0)).get(10)));
                System.out.println(String.valueOf(((Vector) data.get(0)).get(9)));
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlRegistro = new javax.swing.JPanel();
        lblRegistroUsuario = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellido_1 = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        lblApellidos_2 = new javax.swing.JLabel();
        txtApellidos2 = new javax.swing.JTextField();
        lblParqueadero = new javax.swing.JLabel();
        lblIdRol = new javax.swing.JLabel();
        lblApto = new javax.swing.JLabel();
        txtParqueadero = new javax.swing.JTextField();
        cmbApto = new javax.swing.JComboBox<>();
        cmbRol = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlRegistro.setBackground(new java.awt.Color(0, 153, 204));

        lblRegistroUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRegistroUsuario.setText("REGISTRO DE USUARIOS");

        lblNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombres.setText("Nombres");

        lblApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApellidos.setText("Primer Apellido");

        lblId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblId.setText("Identificación");

        lblCel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCel.setText("Celular");

        jLabel3.setBackground(new java.awt.Color(0, 153, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\robert\\Documents\\NetBeansProjects\\SIP\\src\\img\\user.png")); // NOI18N
        jLabel3.setDoubleBuffered(true);

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblApellidos_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApellidos_2.setText("Segundo Apellido");

        lblParqueadero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParqueadero.setText("N° Parqueadero");

        lblIdRol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdRol.setText("Rol");

        lblApto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApto.setText("Apartamento");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroLayout = new javax.swing.GroupLayout(pnlRegistro);
        pnlRegistro.setLayout(pnlRegistroLayout);
        pnlRegistroLayout.setHorizontalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblRegistroUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlRegistroLayout.createSequentialGroup()
                                    .addComponent(lblApellidos)
                                    .addGap(29, 29, 29))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                                    .addComponent(lblApellidos_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                                    .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCel)
                                        .addComponent(lblId)
                                        .addComponent(lblParqueadero)
                                        .addComponent(lblIdRol)
                                        .addComponent(lblApto))
                                    .addGap(35, 35, 35)))
                            .addGroup(pnlRegistroLayout.createSequentialGroup()
                                .addComponent(lblNombres)
                                .addGap(78, 78, 78)))
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtApellidos2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(txtApellido_1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(txtCel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(txtParqueadero)
                                .addComponent(cmbApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnRegistrar)
                        .addGap(35, 35, 35)
                        .addComponent(btnActualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRegistroLayout.setVerticalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegistroLayout.createSequentialGroup()
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistroLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblRegistroUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombres)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidos)
                            .addComponent(txtApellido_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidos_2))
                        .addGap(29, 29, 29)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId))
                        .addGap(34, 34, 34)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCel)
                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblParqueadero)
                            .addComponent(txtParqueadero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApto)
                            .addComponent(cmbApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdRol)
                            .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnActualizar))))
                .addGap(151, 151, 151))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Usuario item = new Usuario();
        item.Apellido1 = txtApellido_1.getText().trim();
        item.Apellido2 = txtApellidos2.getText().trim();
        item.Nombres = txtNombres.getText().trim();
        item.NumeroParqueadero = txtParqueadero.getText().trim();
        item.Telefono = txtCel.getText().trim();
        item.setIdentificacion(Integer.parseInt(txtId.getText().trim()));
        item.setIdRol(Integer.parseInt(cmbRol.getSelectedItem().toString().split("-")[0].trim()));
        item.setIdApartamento(Integer.parseInt(cmbApto.getSelectedItem().toString().split("-")[0].trim()));

        if (item.Insertar() > 0) {
            JOptionPane.showMessageDialog(null, "Usuario almacenado");
            this.limpiarCampos();
            new Database().onLoadTable(jTable2, "SELECT u.nombres,u.apellido_1 'Primer Apellido',u.apellido_2 'Segundo Apellido',u.identificacion,u.telefono,u.num_parqueadero, concat(a.torre,a.num_apto) Apartamento, r.Nombre Tipo FROM usuario u INNER JOIN apartamento a ON u.idApartamento = a.idApto INNER JOIN rol r ON r.idRol = u.idRol");

        } else {
            JOptionPane.showMessageDialog(null, "Tenemos problemas de almacenamiento :(");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        it.Apellido1 = txtApellido_1.getText().trim();
        it.Apellido2 = txtApellidos2.getText().trim();
        it.Nombres = txtNombres.getText().trim();
        it.NumeroParqueadero = txtParqueadero.getText().trim();
        it.Telefono = txtCel.getText().trim();
        it.setIdentificacion(Integer.parseInt(txtId.getText().trim()));
        it.setIdRol(Integer.parseInt(cmbRol.getSelectedItem().toString().split("-")[0].trim()));
        it.setIdApartamento(Integer.parseInt(cmbApto.getSelectedItem().toString().split("-")[0].trim()));

        if (it.Actualizar() > 0) {
            JOptionPane.showMessageDialog(null, "Usuario actualizado");
            this.limpiarCampos();
            new Database().onLoadTable(jTable2, "SELECT u.nombres,u.apellido_1 'Primer Apellido',u.apellido_2 'Segundo Apellido',u.identificacion,u.telefono,u.num_parqueadero, concat(a.torre,a.num_apto) Apartamento, r.Nombre Tipo FROM usuario u INNER JOIN apartamento a ON u.idApartamento = a.idApto INNER JOIN rol r ON r.idRol = u.idRol");

        } else {
            JOptionPane.showMessageDialog(null, "Tenemos problemas de almacenamiento :(");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed
    public void limpiarCampos() {
        txtNombres.setText("");
        txtApellido_1.setText("");
        txtApellidos2.setText("");
        txtId.setText("");
        txtCel.setText("");
        txtParqueadero.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbApto;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidos_2;
    private javax.swing.JLabel lblApto;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdRol;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblParqueadero;
    private javax.swing.JLabel lblRegistroUsuario;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JTextField txtApellido_1;
    private javax.swing.JTextField txtApellidos2;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtParqueadero;
    // End of variables declaration//GEN-END:variables
}
